--- 
spring:
  # h2 db
  h2:
    console:
      enabled : true
      path    : /h2
  # datasource
  datasource:
    url               : jdbc:h2:file:~/test
    username          : sa
    password          :
    driver-class-name : org.h2.Driver